export const actionsEnum = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    ADD: 'ADD_COUNTER',
    SUBTRACT: 'SUB_COUNTER',
    STORE_RESULT: 'STORE_RESULT',
    DELETE_RESULT: 'DELETE_RESULT'
};

